const CATEGORY_RULES=[['Fruta y verdura',/tomate|pepino|cebolla|ajo|zanahoria|pimiento|calabacin|berenjena|espinaca|lechuga|aguacate|boniato|batata|patata|maiz|uva|fruta|verdura|cilantro|perejil|limon/],['Carne y pescado',/pollo|pavo|carne|vacuno|cerdo|hamburguesa|atun|salmon|merluza|gambon|langostino|pescado/],['Lácteos y huevos',/leche|yogur|queso|nata|mantequilla|huevo/],['Panadería',/pan|brioche|tortilla de trigo/],['Despensa',/arroz|pasta|cuscus|lenteja|garbanzo|aceite|vinagre|sal|azucar|miel|salsa|mayonesa|ketchup|mermelada|aceituna|harina/],['Bebidas',/agua|zumo|refresco|nestea|cerveza|vino|cafe|te/]];
export function normalizeName(value){return String(value||'').toLocaleLowerCase('es-ES').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/^tr\s+/,'').replace(/\([^)]*\)/g,' ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim()}
export function cleanName(value){let v=String(value||'').replace(/^TR\s+/i,'').replace(/\s*\([^)]*\)\s*/g,' ').trim().toLocaleLowerCase('es-ES');return v?v[0].toLocaleUpperCase('es-ES')+v.slice(1):v}
export function categoryFor(name){let n=normalizeName(name);return CATEGORY_RULES.find(([,re])=>re.test(n))?.[0]||'Otros'}
export function unitInfo(raw){let u=normalizeName(raw).replace(/\s/g,''),m={gramo:['g',1],gramos:['g',1],gr:['g',1],g:['g',1],kg:['g',1000],kilo:['g',1000],kilos:['g',1000],mililitro:['ml',1],mililitros:['ml',1],ml:['ml',1],l:['ml',1000],litro:['ml',1000],litros:['ml',1000],unidad:['uds',1],unidades:['uds',1],ud:['uds',1],uds:['uds',1]}[u];return m||[String(raw||'').trim().toLocaleLowerCase('es-ES'),1]}
export function displayAmount(item){let q=Number(item.quantity)||0,u=item.unit||'';if(!q&&!u)return'';if(u==='g'&&q>=1000&&q%100===0){q/=1000;u='kg'}else if(u==='ml'&&q>=1000&&q%100===0){q/=1000;u='l'}return`${(Math.round(q*100)/100).toLocaleString('es-ES')} ${u}`.trim()}
export function makeShopping(days,people=2,titleFor=()=> ''){let grouped=new Map;for(const day of days||[])for(const[meal,ingredients]of Object.entries(day.meals||{}))for(const ingredient of ingredients||[]){let name=cleanName(ingredient.name),[unit,factor]=unitInfo(ingredient.unit),quantity=Number(ingredient.qty)*people*factor;if(!name||!Number.isFinite(quantity))continue;let key=`${normalizeName(name)}|${unit}`,origin={day:day.name,date:day.date,meal,recipe:titleFor(day,meal)},existing=grouped.get(key);if(existing){existing.quantity+=quantity;if(!existing.origins.some(x=>x.date===origin.date&&x.meal===origin.meal))existing.origins.push(origin)}else grouped.set(key,{id:key,name,quantity,unit,category:categoryFor(name),selected:true,origins:[origin]})}return[...grouped.values()].sort((a,b)=>a.category.localeCompare(b.category,'es')||a.name.localeCompare(b.name,'es'))}
export function buyLine(item){let amount=displayAmount(item);return amount?`${item.name} (${amount})`:item.name}
export function selectedText(items){return(items||[]).filter(x=>x.selected).map(buyLine).join('\n')}
export function selectedPayload(items){return(items||[]).filter(x=>x.selected).map(x=>({name:x.name,quantity:displayAmount(x),category:x.category}))}
