import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const html=await readFile('index.html','utf8');
const manifest=JSON.parse(await readFile('manifest.webmanifest','utf8'));
const repoText=await Promise.all(['index.html','README.md','sw.js','manifest.webmanifest'].map(f=>readFile(f,'utf8'))).then(a=>a.join('\n'));
test('no publica la dieta ni conexiones remotas',()=>{assert.doesNotMatch(repoText,/1drv\.ms|onedrive|sharepoint|data\.json|fetch\(`data/i);assert.match(html,/type="file"/);assert.match(html,/parseWorkbook/)});
test('funde la parte superior con el gris del navegador',()=>{assert.match(html,/name="theme-color" content="#f2f3f6"/);assert.match(html,/linear-gradient\(to bottom,#f2f3f6 0/)});
test('simplifica títulos y capitaliza ingredientes',()=>{assert.match(html,/function titlePart/);assert.match(html,/presets=/);assert.match(html,/function clean\(s\)\{return cap\(/)});
test('configura iPhone y PWA para cubrir la zona segura',()=>{for(const v of ['viewport-fit=cover','black-translucent','safe-area-inset-top','100dvh','overscroll-behavior','display-mode:standalone'])assert.match(html,new RegExp(v))});
test('declara iconos PWA válidos para iPhone y navegadores',async()=>{assert.match(html,/<link rel="apple-touch-icon" sizes="180x180" href="\.\/apple-touch-icon\.png\?v=3">/);assert.deepEqual(manifest.icons.map(({src,sizes,type})=>({src,sizes,type})),[{src:'./icon-192.png',sizes:'192x192',type:'image/png'},{src:'./icon-512.png',sizes:'512x512',type:'image/png'}]);for(const [file,size] of [['apple-touch-icon.png',180],['icon-192.png',192],['icon-512.png',512]]){const png=await readFile(file);assert.equal(png.subarray(1,4).toString(),'PNG');assert.equal(png.readUInt32BE(16),size);assert.equal(png.readUInt32BE(20),size)}});
test('usa Europe Madrid para identificar hoy sin UTC',()=>{assert.match(html,/ZONE='Europe\/Madrid'/);assert.match(html,/function madridToday/);assert.doesNotMatch(html,/function iso\(d\).*toISOString/)});
test('mantiene vistas y metadatos',()=>{for(const v of ['Hoy','Semana','2 personas','Comida','Cena','Desayuno','Media mañana','Merienda','Tiempo aproximado','Preparar con antelación','Notas'])assert.match(html,new RegExp(v))});
test('semana apila y abre cada receta',()=>{assert.match(html,/grid-template-columns:48px minmax\(0,1fr\)/);assert.match(html,/openDlg\(d,t\)/);assert.match(html,/weekMeal\(d,'Comida'/);assert.doesNotMatch(html,/grid-template-columns:48px 1fr 1fr/)});
