import AnyListPackage from'anylist';
const AnyList=AnyListPackage.default||AnyListPackage,LIST_NAME='Lista de la compra';
const json=(data,status=200)=>Response.json(data,{status,headers:{'cache-control':'no-store'}});
const canonical=value=>String(value||'').trim().toLocaleLowerCase('es-ES');
const uuid=()=>crypto.randomUUID().replaceAll('-','');
const encoder=new TextEncoder();
const loginPage=`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f2f3f6"><title>Dieta · Acceso</title><style>*{box-sizing:border-box}body{margin:0;min-height:100dvh;display:grid;place-items:center;background:#f2f3f6;font:16px system-ui;color:#172033}.box{width:min(92%,390px);padding:32px;border-radius:28px;background:#fff;box-shadow:0 18px 60px #1d2b4f20}h1{margin:0 0 8px;font-size:34px}p{color:#697386}input,button{width:100%;min-height:50px;border-radius:14px;font:inherit}input{border:1px solid #d7dce5;padding:0 15px;margin:14px 0}button{border:0;background:#2257d5;color:white;font-weight:700}#e{color:#b42318}</style><main class="box"><h1>Dieta</h1><p>Acceso privado</p><form><input type="password" autocomplete="current-password" placeholder="Contraseña" required><button>Entrar</button><p id="e"></p></form></main><script>document.querySelector('form').onsubmit=async e=>{e.preventDefault();let b=document.querySelector('button'),p=document.querySelector('input');b.disabled=true;let r=await fetch('/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:p.value})});if(r.ok)location.reload();else{document.querySelector('#e').textContent='Contraseña incorrecta';b.disabled=false}}</script></html>`;
const b64=bytes=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
async function mac(value,secret){let key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(value))))}
async function idempotencyKey(requestId){return`send:${b64(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(requestId))))}`}
async function equal(a,b){if(typeof b!=='string'||!b)return false;let[x,y]=await Promise.all([crypto.subtle.digest('SHA-256',encoder.encode(a)),crypto.subtle.digest('SHA-256',encoder.encode(b))]),xa=new Uint8Array(x),ya=new Uint8Array(y),diff=0;for(let i=0;i<xa.length;i++)diff|=xa[i]^ya[i];return diff===0}
async function authenticated(request,env){let raw=request.headers.get('cookie')?.match(/(?:^|; )dieta_session=([^;]+)/)?.[1];if(!raw)return false;let[expires,signature]=raw.split('.');return Number(expires)>Date.now()&&signature===await mac(expires,env.DIETA_SESSION_SECRET)}

function adapt(client,email,password){
  client.authClient={post(path){return{async json(){let form=new FormData();if(path==='auth/token'){form.set('email',email);form.set('password',password)}else form.set('refresh_token',client.refreshToken);let response=await fetch(`https://www.anylist.com/${path}`,{method:'POST',headers:{'X-AnyLeaf-API-Version':'3'},body:form});if(!response.ok)throw Error(`AnyList auth ${response.status}`);return response.json()}}}};
  client.client={async post(path){let response=await fetch(`https://www.anylist.com/${path}`,{method:'POST',headers:headers(client)});if(!response.ok)throw Error(`AnyList ${path} ${response.status}`);return{body:Buffer.from(await response.arrayBuffer())}}};
}
function headers(client){return{'X-AnyLeaf-API-Version':'3','X-AnyLeaf-Client-Identifier':client.clientId,authorization:`Bearer ${client.accessToken}`}}
function operation(client,list,item,handler){let op=new client.protobuf.PBListOperation();op.setMetadata({operationId:uuid(),handlerId:handler,userId:client.uid});op.setListId(list.identifier);op.setListItemId(item.identifier);op.setListItem(item._encode());return op}
async function sendOperations(client,operations){let list=new client.protobuf.PBListOperationList();list.setOperations(operations);let bytes=new Uint8Array(list.toBuffer()),boundary=`--------------------------${uuid()}`,encoder=new TextEncoder(),prefix=encoder.encode(`--${boundary}\r\nContent-Disposition: form-data; name="operations"\r\nContent-Type: application/octet-stream\r\n\r\n`),suffix=encoder.encode(`\r\n--${boundary}--\r\n`),body=new Uint8Array(prefix.length+bytes.length+suffix.length);body.set(prefix);body.set(bytes,prefix.length);body.set(suffix,prefix.length+bytes.length);let response=await fetch('https://www.anylist.com/data/shopping-lists/update',{method:'POST',headers:{...headers(client),'Content-Type':`multipart/form-data; boundary=${boundary}`},body});if(!response.ok)throw Error(`AnyList update ${response.status}`)}
function validate(items){if(!Array.isArray(items)||items.length>250)throw Error('Lista no válida');return items.map(x=>({name:String(x.name||'').trim().slice(0,160),quantity:String(x.quantity||'').trim().slice(0,60)})).filter(x=>x.name)}
function classify(list,items){let find=name=>list.items.find(x=>canonical(x.name)===canonical(name));return items.reduce((out,item)=>{let match=find(item.name);if(!match)out.new.push(item);else if(match.checked)out.completed.push(item);else out.active.push(item);return out},{new:[],active:[],completed:[]})}
async function session(env,work){let client=new AnyList({email:env.ANYLIST_EMAIL,password:env.ANYLIST_PASSWORD,credentialsFile:null});adapt(client,env.ANYLIST_EMAIL,env.ANYLIST_PASSWORD);try{await client.login(false);await client.getLists();let list=client.getListByName(LIST_NAME);if(!list)throw Error(`No existe “${LIST_NAME}”`);return await work(client,list)}finally{client.teardown()}}
async function apply(client,list,items){let groups=classify(list,items),ops=[];for(const value of groups.new){let item=client.createItem(value);item.listId=list.identifier;ops.push(operation(client,list,item,'add-shopping-list-item'))}for(const value of groups.completed){let old=list.items.find(x=>canonical(x.name)===canonical(value.name)),fresh=client.createItem({...value,categoryMatchId:old.categoryMatchId,categoryAssignments:old.categoryAssignments,storeIds:old.storeIds,checked:false});fresh.listId=list.identifier;ops.push(operation(client,list,old,'remove-shopping-list-item'),operation(client,list,fresh,'add-shopping-list-item'))}if(ops.length)await sendOperations(client,ops);await client.getLists(true);let refreshed=client.getListByName(LIST_NAME),missing=[...groups.new,...groups.completed].filter(x=>!refreshed.items.some(y=>canonical(y.name)===canonical(x.name)&&String(y.quantity||'').trim()===x.quantity));if(missing.length)throw Error(`AnyList no confirmó: ${missing.map(x=>x.name).join(', ')}`);return{added:groups.new.length,reactivated:groups.completed.length,skipped:groups.active.length,active:groups.active}}

export default{async fetch(request,env){let url=new URL(request.url);if(url.pathname==='/auth/login'&&request.method==='POST'){let{password}=await request.json();if(!await equal(String(password||''),env.DIETA_ACCESS_PASSWORD))return json({error:'No autorizado'},401);let expires=String(Date.now()+2592000000),signature=await mac(expires,env.DIETA_SESSION_SECRET);return new Response(null,{status:204,headers:{'set-cookie':`dieta_session=${expires}.${signature}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=2592000`}})}if(!await authenticated(request,env))return new Response(loginPage,{status:401,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}});if(!url.pathname.startsWith('/api/'))return env.ASSETS.fetch(request);if(request.method!=='POST')return json({error:'Método no permitido'},405);try{let payload=await request.json(),items=validate(payload.items);if(!items.length)return json({error:'No hay productos seleccionados'},400);if(url.pathname==='/api/anylist/preview')return json(await session(env,(_client,list)=>classify(list,items)));if(url.pathname!=='/api/anylist/send')return json({error:'No encontrado'},404);let requestId=String(payload.requestId||'');if(!requestId)return json({error:'Falta identificador'},400);let key=await idempotencyKey(requestId),prior=await env.SEND_STATE.get(key,'json');if(prior)return json({...prior,duplicate:true});let result=await session(env,(client,list)=>apply(client,list,items));await env.SEND_STATE.put(key,JSON.stringify(result),{expirationTtl:2592000});return json(result)}catch(error){console.error(JSON.stringify({event:'anylist_error',message:error?.message}));return json({error:error?.message||'Error interno'},500)}}};
